---
- name: preflight
  ansible.builtin.include_tasks:
    file: preflight.yml

- name: install nomad
  ansible.builtin.include_tasks:
    file: install.yml

- name: configure nomad
  ansible.builtin.include_tasks:
    file: configure.yml

- name: start nomad cluster
  ansible.builtin.include_tasks:
    file: start.yml
  when:
    - nomad_server | bool
