---
- name: select leader if nomad_leader is unset
  ansible.builtin.set_fact:
    nomad_leader: "{{ inventory_hostname }}"
  run_once: true
  when:
    - nomad_leader is not defined

- name: print elected leader
  ansible.builtin.debug:
    msg: "{{ nomad_leader }}"
